--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimpleEco
build-by-default: true
branches:
- master
projects:
  SimpleEco:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.4.0
        branch: "4.0"
    lint:
      phpstan: false
...
